pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                script {
                    echo "Deploying ${JOB_NAME} with ${ENV_VARIABLE}"
                    sh "./mvnw clean package"
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    sh "./mvnw test"
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    def jarFile = 'target/geolocation-service-1.0.0-RELEASE.jar'
                    if (fileExists(jarFile)) {
                        sh "java -jar ${jarFile}"
                    } else {
                        error "JAR file not found, aborting deployment."
                    }
                }
            }
        }
    }
    post {
        success {
            script {
                echo 'Build and deployment were successful.'
            }
        }
        failure {
            script {
                echo 'Build or deployment failed.'
            }
        }
    }
}
